[project]
name = "uploadweb"
version = "1.2.0"
description = "A file upload tool for personal use. It allows users to upload files through a web page to Google Cloud Storage (GCS) and provides temporary download links."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "functions-framework>=3.10.2",
    "google-auth>=2.56.2",
    "google-cloud-storage>=3.13.0",
]
